### PR TITLE
Set up Server

### PR DESCRIPTION
**Pull request by Danwhy**
Adds basic hapi server for serving static files

ref #10

### CODE REVIEW

**Review by sohilpandya — APPROVED** [review]
LGTM :)

**Comment by sohilpandya** [comment]
@Danwhy, the above looks good, just have a couple of questions around setup:
- We don't have scripts in package.json to start the server. 
- we'll probably need to proxy the server so that we can access it during development. https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development

Here are a few things that we may need:
```
    "start": "node server.js",
    "start:back": "nodemon server.js",
    "start:front": "NODE_PATH=src/ react-scripts start",
    "start:dev": "concurrently \"npm run start:back\" \"npm run start:front\"",
    "heroku-postbuild": "npm install && npm install --only=dev --no-shrinkwrap && npm run build"
```

If we are to push this to heroku, we'll need to change the `start` script to run just the server and the `heroku-postbuild` to run the build. 

concurrently is just a nice to have when you want to run the dev build. 

Again, you may have already tackled this in a future PR in that case please ignore it. 😬 

Let me know and if all is ok then I can merge this in. :)

**Comment by Danwhy** [comment]
@sohilpandya I have taken care of some of this in an upcoming PR, but that's some useful info that I will also use, thanks. This one can be merged for now

**Comment by sohilpandya** [comment]
Thanks for the update. will merge now :)

**Pull request merged**
